== Migrate custom content from Drupal 7 to Drupal 8

=== Prepare web environment - Apache + PHP + MysSQL

. Install required packages:

 $ zypper in apache2 apache2-mod_php7 php7-gd php7-mysql \
  mysql-community-server php-composer

. Edit Apache's configuration file '/etc/apache2/default-server.conf' and replace `AllowOverride None` with `AllowOverride All`, and `Options None` with `Options FollowSymLinks`.

. Enable required Apache modules:

 $ a2enmod php7 access_compat rewrite

. Restart Apache and MySQL services:

 $ systemctl restart apache2.service mysql.service

. Download and install Drupal 7
 .. Extract Drupal 7 in the '/srv/www/htdocs/drupal7/' directory.
 .. Create Apache-writeable directory and writeble settings file:

 $ mkdir /srv/www/htdocs/drupal7/sites/default/files
 $ chown -R wwwrun /srv/www/htdocs/drupal7/sites/default/files
 $ cp /srv/www/htdocs/drupal7/sites/default/default.settings.php \
  /srv/www/htdocs/drupal7/sites/default/settings.php
 $ chown wwwrun /srv/www/htdocs/drupal7/sites/default/settings.php

 .. Install Drupal 7 by pointing your browser to http://localhost/drupal7/.

. Download and install Drupal 8
 .. Extract Drupal 8 in the '/srv/www/htdocs/drupal8/' directory.
 .. Create Apache-writeable directory and writeable settings file:

  $ mkdir /srv/www/htdocs/drupal8/sites/default/files
  $ chown -R wwwrun /srv/www/htdocs/drupal7/sites/default/files
  $ cp /srv/www/htdocs/drupal8/sites/default/default.settings.php \
   /srv/www/htdocs/drupal8/sites/default/settings.php
  $ chown wwwrun /srv/www/htdocs/drupal8/sites/default/settings.php

 .. Install Drupal 8 by pointing your browser to http://localhost/drupal8/.

. Install `drush` locally for the Drupal 8 instance. Run the following command
in the root directory of the Drupal 8 installation:

 $ composer require drush/drush

. Install Drupal Console locally for the Drupal 8 instance. Run the following command
 in the root directory of the Drupal 8 installation:

 $ composer require drupal/console:~1.0 --prefer-dist --optimize-autoloader --sort-packages

. Enable the following module in our Drupal 8 site:

 $ drush pm-enable migrate migrate_drupal migrate_upgrade migrate_tools migrate_plus

[[db_definition]]
=== Add required database definitions

Add the following code (supply the right credentials) to the Drupal 8 'settings.php' file:

----
// Database entry for `drush migrate-upgrade --configure-only`
$databases['upgrade']['default'] = array (
  'database' => 'drupal7',
  'username' => 'drupal7',
  'password' => 'drupal7',
  'prefix' => '',
  'host' => 'localhost',
  'port' => '3306',
  'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
  'driver' => 'mysql',
);
// Database entry for `drush migrate-import --all`
$databases['migrate']['default'] = array (
  'database' => 'drupal7',
  'username' => 'drupal7',
  'password' => 'drupal7',
  'prefix' => '',
  'host' => 'localhost',
  'port' => '3306',
  'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
  'driver' => 'mysql',
);
----

=== Generate a migration

From your Drupal 8 directory, run:

 $ drush migrate-upgrade --configure-only

[TIP]
====
If you did not add an entry in your 'settings.php' as described in
<<db_definition>>, you can pass the Drupal 7 database credentials, and optionally, the path to
the files directory:

 $ drush migrate-upgrade --configure-only \
  --legacy-db-url=mysql://dbuser:dbpass@localhost/dbname \
  --legacy-root=/path/to/sites/default/files
====
