== Migrate custom content from Drupal 7 to Drupal 8

=== Prepare web environment - Apache + PHP + MysSQL

. Install required packages:

 $ zypper in apache2 apache2-mod_php7 php7-gd php7-mysql \
  mysql-community-server php-composer

. Edit Apache's configuration file '/etc/apache2/default-server.conf' and
replace `AllowOverride None` with `AllowOverride All`, and `Options None` with
`Options FollowSymLinks`.

. Enable required Apache modules:

 $ a2enmod php7 access_compat rewrite

. Restart Apache and MySQL services:

 $ systemctl restart apache2.service mysql.service

. Download and install Drupal 7
 .. Extract Drupal 7 in the '/srv/www/htdocs/drupal7/' directory.
 .. Create Apache-writeable directory and writeble settings file:

 $ mkdir /srv/www/htdocs/drupal7/sites/default/files
 $ chown -R wwwrun /srv/www/htdocs/drupal7/sites/default/files
 $ cp /srv/www/htdocs/drupal7/sites/default/default.settings.php \
  /srv/www/htdocs/drupal7/sites/default/settings.php
 $ chown wwwrun /srv/www/htdocs/drupal7/sites/default/settings.php

 .. Install Drupal 7 by pointing your browser to http://localhost/drupal7/.

. Download and install Drupal 8
 .. Extract Drupal 8 in the '/srv/www/htdocs/drupal8/' directory.
 .. Create Apache-writeable directory and writeable settings file:

  $ mkdir /srv/www/htdocs/drupal8/sites/default/files
  $ chown -R wwwrun /srv/www/htdocs/drupal7/sites/default/files
  $ cp /srv/www/htdocs/drupal8/sites/default/default.settings.php \
   /srv/www/htdocs/drupal8/sites/default/settings.php
  $ chown wwwrun /srv/www/htdocs/drupal8/sites/default/settings.php

 .. Install Drupal 8 by pointing your browser to http://localhost/drupal8/.

. Install `drush` globally on your system:

 $ composer global require drush/drush

. Install Drupal Console globally:

 $ composer global require drupal/console:~1.0 --prefer-dist --optimize-autoloader --sort-packages

. Enable the following module in our Drupal 8 site:

 $ drush pm-enable migrate migrate_drupal migrate_upgrade migrate_tools migrate_plus

[[db_definition]]
=== Add required database definitions

Add the following code (supply the right credentials) to the Drupal 8 'settings.php' file:

----
// Database entry for `drush migrate-upgrade --configure-only`
$databases['upgrade']['default'] = array (
  'database' => 'drupal7',
  'username' => 'drupal7',
  'password' => 'drupal7',
  'prefix' => '',
  'host' => 'localhost',
  'port' => '3306',
  'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
  'driver' => 'mysql',
);
// Database entry for `drush migrate-import --all`
$databases['migrate']['default'] = array (
  'database' => 'drupal7',
  'username' => 'drupal7',
  'password' => 'drupal7',
  'prefix' => '',
  'host' => 'localhost',
  'port' => '3306',
  'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
  'driver' => 'mysql',
);
----

=== Generate a migration

From your Drupal 8 directory, run:

 $ drush migrate-upgrade --configure-only

The command generates migration configuration entities in the active
configuration store.

[TIP]
====
If you did not add an entry in your 'settings.php' as described in
<<db_definition>>, you can pass the Drupal 7 database credentials, and optionally, the path to
the files directory:

 $ drush migrate-upgrade --configure-only \
  --legacy-db-url=mysql://dbuser:dbpass@localhost/dbname \
  --legacy-root=/path/to/sites/default/files
====

=== Create a custom migration module

Create a custom module in your Drupal 8 site. You can do it either manually, or
using Drupal Console:

----
./drupal generate:module

 // Welcome to the Drupal module generator

 Enter the new module name:
 > custom_migration

 Enter the module machine name [custom_migration]:
 >

 Enter the module Path [/modules/custom]:
 >

 Enter module description [My Awesome Module]:
 > A custom Drupal 7 to 8 migration

 Enter package name [Custom]:
 >

 Enter Drupal Core version [8.x]:
 >

 Do you want to generate a .module file (yes/no) [yes]:
 >

 Define module as feature (yes/no) [no]:
 >

 Do you want to add a composer.json file to your module (yes/no) [yes]:
 >

 Would you like to add module dependencies (yes/no) [no]:
 > yes

 Module dependencies separated by commas (i.e. context, panels):
 > migrate_drupal, migrate_plus

 Do you want to generate a unit test class (yes/no) [yes]:
 > no

 Do you want to generate a themeable template (yes/no) [yes]:
 > no

 Do you confirm generation? (yes/no) [yes]:
 >

Generated or updated files

 1 - /srv/www/htdocs/drupal8/modules/custom/custom_migration/custom_migration.info.yml
 2 - /srv/www/htdocs/drupal8/modules/custom/custom_migration/custom_migration.module
 3 - /srv/www/htdocs/drupal8/modules/custom/custom_migration/composer.json
----

=== Export Drupal 8 site configuration

Create the directory 'custom_migration/config/install' where you will
store the custom migration. You can now export Drupal 8 site configuration, which will
include your generated migration configuration entities:

 $ drush config-export --destination=/tmp/migrate

=== Copy migration configuration to the custom module

Next, you need to copy the migration configuration generated by `drush
migrate-upgrade --configure-only` to the 'custom_migrate/config/install'
directory. The files are in '/tmp/migrate/' and their file names begin with 
'migrate_plus*'.

[WARNING]
====
Make sure you do not copy the default configuration group that is defined by
the Migrate Plus module, i.e. 'migrate_plus.migration_group.default.yml'.

Use the following command replacing the last argument with the correct path
to your custom module's 'config/install' location:

 $ cp /tmp/migrate/migrate_plus.migration.* \
  /tmp/migrate/migrate_plus.migration_group.migrate_*.yml \
  module/custom/config/install/
====

=== Edit the migrations in the custom modules

At this point, you can simply remove any of the migrations you do not need, along
with any dependencies on them. You can also now edit the migrations contained in
your module to your liking.

For example, if you do not want to migrate blocks from your previous site, you
would delete the following files at 'custom_migration/config/install':

----
migrate_plus.migration.upgrade_block_content_body_field.yml
migrate_plus.migration.upgrade_block_content_type.yml
migrate_plus.migration.upgrade_d7_block.yml
migrate_plus.migration.upgrade_d7_custom_block.yml
----

==== Customize migrations with process plugins (optional)

You can customize migrations with process plugins.

For example, let us assume you are migrating from a Drupal 7 site and you want
to map a node type from a previous Drupal version to a different node type in
Drupal 8 you could accomplish this with the `default_value` process plugin.

For example, given this migration template:

 migrate_plus.migration.upgrade_d7_node_blog_post.yml

In the `process:` section of the migration, note the following:

 process:
   type: type
   name: name
   description: description
 ...

Instead of mapping the node type in Drupal 7 to one of the same name in Drupal
8, which would import the `blog_post` content from Drupal 7 to a content type of
`blog_post` in Drupal 8, we can use the `default_value` plugin, and specify
a node type of a different name.

In the `process:` key, change the values for `plugin:` to `default_value` and
`value:` to the machine name of your desired node type.

 process:
   type:
     plugin: default_value
     value: desired_node_type
   name: name
   description: description
   help: help
   title_label: title_label
   preview_mode: constants/preview
   display_submitted: display_submitted
   new_revision: options/revision
   create_body: create_body
   create_body_label: body_label

=== TODO
* clean way to load the filtered files (must include the 'group' file!!!)
* redeploy the migration after the source content type changes
* transfer images, taxonomy references and paragraphs
